build: false

environment:
  PYTHON: "C:\\myminiconda3"
  matrix:
    - PY: 2.7
    - PY: 3.7

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  # Add path, activate `conda` and update conda.
  - set URL="https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe"
  - curl -fsS -o miniconda3.exe %URL%
  - start /wait "" miniconda3.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%PYTHON%

  - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - call %PYTHON%\Scripts\activate

  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda config --add channels conda-forge --force
  - conda config --set channel_priority strict
  - set PYTHONUNBUFFERED=1

  - python gen_conda_requirements.py --groups requirements.txt --py%PY:~0,1% > conda-requirements.txt
  - conda create --name TEST python=%PY% --file conda-requirements.txt --file test_requirements.txt

  - conda activate TEST
  - conda info --all
  - conda list


test_script:
  - python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  - pytest -s -rxs -v -k "not integration" compliance_checker
