language: python

sudo: false

env:
    - CONDA="python=2.7"
    - CONDA="python=3.4"
    - CONDA="python=3.5"

before_install:
    - URL=http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
    - wget $URL -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes --all
    - conda config --add channels conda-forge --force
    - travis_retry conda create --yes -n test --file requirements.txt $CONDA
    - travis_retry conda install -n test --yes pytest flake8
    - source activate test

install:
    - pip install -r requirements.txt
    - pip install -e .

script:
    - py.test -s -rxs -v
    - flake8 --ignore=E501,E251,E221,E201,E202,E203 -qq --statistics . || true
